image: golang:latest

variables:
  REPO_NAME: gitlab.com/shackra/goimapnotify

stages:
  - test

testing:
  stage: test
  script:
    - go vet ./...
    - go build -v
    - go test -coverprofile goimapnotify

merge_guard:
  stage: test
  image: alpine:latest
  script:
    - apk add --no-cache curl jq bc
    - |
      MR_API_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}"
      MR_INFO=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$MR_API_URL")
      
      TITLE=$(echo "$MR_INFO" | jq -r .title)
      CREATED_AT=$(echo "$MR_INFO" | jq -r .created_at)
      
      VALID_PREFIXES="^(fix:|new:|chg:|perf:|refactor:|BREAKING CHANGE|draft:)"
      if ! echo "$TITLE" | grep -Eq "$VALID_PREFIXES"; then
        echo "❌ MR title is missing a valid prefix."
        exit 1
      fi

      CLEAN_DATE=$(echo "$CREATED_AT" | sed -E 's/T/ /; s/\.[0-9]+Z$//')
      CREATED_TIMESTAMP=$(date -d "$CLEAN_DATE" +%s)
      NOW_TIMESTAMP=$(date +%s)
      AGE_SECONDS=$((NOW_TIMESTAMP - CREATED_TIMESTAMP))
      AGE_HOURS=$(echo "scale=2; $AGE_SECONDS / 3600" | bc)
      
      if echo "$AGE_HOURS < 8" | bc -l | grep -q 1; then
        echo "❌ MR has to be at least 8 hours old, and this one is $AGE_HOURS hour(s)... come back later :)"
        exit 1
      fi
      
      echo "✅ MR fulfills all the requirements."
  only:
    - merge_requests
