image: golang:latest

variables:
  REPO_NAME: gitlab.com/shackra/goimapnotify

stages:
  - test

testing:
  stage: test
  script:
    - go vet ./...
    - go build -v
    - go test -coverprofile goimapnotify
